name: delete-old

on:
  workflow_dispatch:

jobs:

  delete:

    runs-on: ubuntu-latest
    
    steps:
    - name: Prune
      uses: vlaurin/action-ghcr-prune@v0.6.0
      with:
        token: ${{ secrets.DELETE_TOKEN }}
        organization: ""
        container: gnu-on-alpine
        dry-run: true # Dry-run first, then change to `false`
        keep-younger-than: 180 # days
        prune-untagged: true
