name: delete-old

on:
  workflow_dispatch:

jobs:

  delete:

    runs-on: ubuntu-latest
    
    steps:
    - name: Prune
      uses: vlaurin/action-ghcr-prune@v0.4.0
      with:
        token: ${{ secrets.DELETE_TOKEN }}
        organization: ""
        container: pyaction-lite
        dry-run: true # Dry-run first, then change to `false`
        older-than: 1 # days
        untagged: true
