name: build

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cicirello/gnu-on-alpine:$(date +%s)
